### ISSUE TITLE
Pick name for MLO device adapter

### ISSUE THREAD

**Issue by ieivanov** [mehta-lab/mmCoreAndDevices#3]
The current name of the MLO device adapter is `MeadowlarkLcOpenSource`, which is a bit awkward. We could rename it to `MeadowlarkLC`, which is cleaner. This would require updating the `LC_DEVICE_NAME` constant in `recOrder`. Existing `recOrder` installation will continue to work unless recOrder is updated. We can instruct new users to install recOrder and the latest version of MM, which would both use the renamed `MeadowlarkLC` device adapter. We can instruct the small number of users who would like to use an old version of MM and the latest version of `recOrder` to manually add the `mmgr_dal_MeadowlarkLC.dll` to the MM install folder and delete the old `mmgr_dal_MeadowlarkLcOpenSource.dll` file.

**Comment by talonchandler** [comment]
I'm in favor of renaming to `MeadowlarkLC`, and I'm happy to update `recOrder` when this merges into MM. Thanks for handling this @ieivanov.

**Comment by mattersoflight** [comment]
`MeadowlarkLC` is indeed a good name. Thanks.
