### ISSUE TITLE
Update MLO license and copyright claims

### ISSUE THREAD

**Issue by ieivanov** [mehta-lab/mmCoreAndDevices#4]
Update copyright to cover contributions of MBL and Biohub. Anyone else?

https://github.com/mehta-lab/mmCoreAndDevices/blob/MeadowlarkLC_v107/DeviceAdapters/MeadowlarkLC/license.txt

Also, clean up preamble to `MeadowlarkLC.cpp` and `MeadowlarkLC.h`, model after https://github.com/micro-manager/mmCoreAndDevices/blob/main/DeviceAdapters/TriggerScopeMM/TriggerScopeMM.cpp. 

No need to keep Change Log in that file, as that is now handled by Github.

**Comment by mattersoflight** [comment]
@ieivanov I just updated the license text.  👍🏼 for cleaning up the preamble as you suggest.
